# Optimization workshop with TensorFlow

[tensorflow](https://www.tensorflow.org/) library is an open-source library for machine learning and deep learning, which provides automatic differentiation and efficient numerical computation. 

Let's dive into the basic features to see how it can be used in optimization problems.


### 1. **Tensors**

- **Tensors** are the core data structures in TensorFlow. They are multi-dimensional arrays, similar to NumPy arrays, that represent the input data, model parameters, and intermediate outputs in a TensorFlow computation graph.
  
- In TensorFlow, you can create tensors from NumPy arrays, and TensorFlow automatically tracks their shape and dtype.

In [7]:
# Example
import tensorflow as tf
X = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)  # Create a 2x3 tensor
print(X)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)



### 2. **Variables**

- **Variables** in TensorFlow are tensors whose values can be updated during training (e.g., the model parameters, such as weights or biases). They are used to store the state of a model.

- Variables are trainable, which means TensorFlow can automatically compute the gradients of the loss function with respect to these variables during training.


In [8]:
# Example
beta = tf.Variable(tf.zeros([3, 1], dtype=tf.float32))  # A 3x1 variable (initially zeros)
print(beta)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.],
       [0.],
       [0.]], dtype=float32)>


In [9]:
# Example initializing with random values
beta = tf.Variable(tf.random.normal([3, 1], mean=0.0, stddev=1.0))  # A 3x1 variable (initially random)
print(beta)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 2.257863  ],
       [-1.3283876 ],
       [-0.95160955]], dtype=float32)>


### 3. **Operations**

- **Operations** are functions that take tensors as inputs and produce tensors as outputs. Common operations include matrix multiplication (`tf.matmul`), addition, and the sigmoid function (`tf.sigmoid`).

- These operations define the computation graph, which TensorFlow executes efficiently.

In [10]:
## Example
z = tf.matmul(X, beta)  # Matrix multiplication
print(z)

tf.Tensor(
[[-3.2537408]
 [-3.3201432]], shape=(2, 1), dtype=float32)


In [11]:
print(tf.reduce_sum(tf.matmul(X, beta)))

tf.Tensor(-6.573884, shape=(), dtype=float32)


### 3.1 **Common Tensor Operations**

### a. **Matrix Operations**
   - **Matrix Multiplication**: This is a common operation for combining input features and weights in machine learning models.
     ```python
     X = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
     W = tf.constant([[0.1, 0.2], [0.3, 0.4]], dtype=tf.float32)
     Z = tf.matmul(X, W)  # Matrix multiplication
     ```
   
   - **Transpose**: You may need to transpose tensors for operations.
     ```python
     X_transposed = tf.transpose(X)  # Transpose the tensor
     ```

   - **Element-wise multiplication**: Multiply tensors element-wise.
     ```python
     X = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
     Y = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
     elementwise_mult = tf.multiply(X, Y)  # Element-wise multiplication
     ```



### b. **Element-wise Operations**
   - **Addition and Subtraction**: You can perform element-wise addition and subtraction directly on tensors.
     ```python
     Z = X + Y  # Element-wise addition
     Z = X - Y  # Element-wise subtraction
     ```

   - **Power**: Raise each element of the tensor to a power.
     ```python
     Z = tf.pow(X, 2)  # Square each element in X
     ```

   - **Maximum/Minimum**: Get the element-wise maximum or minimum between two tensors.
     ```python
     Z = tf.maximum(X, Y)  # Element-wise maximum
     ```


### c. **Reshaping and Broadcasting**
   - **Reshape**: Change the shape of a tensor, useful when preparing input data for models.
     ```python
     reshaped_tensor = tf.reshape(X, [1, 4])  # Reshape X into a 1x4 tensor
     ```

   - **Broadcasting**: TensorFlow automatically **broadcasts** smaller tensors to match the shape of larger tensors during operations, allowing element-wise operations between tensors of different shapes.
     ```python
     X = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
     scalar = tf.constant(5.0, dtype=tf.float32)
     Z = X + scalar  # Broadcasts scalar to match X's shape
     ```




### d. **Reduction Operations**
   - **Mean**: Compute the mean of elements along a specific axis or across all elements.
     ```python
     mean_value = tf.reduce_mean(X)  # Compute the mean of all elements in X
     ```

   - **Sum**: Compute the sum of elements along a specific axis or across all elements.
     ```python
     sum_value = tf.reduce_sum(X)  # Sum of all elements in X
     ```

   - **Argmax/Argmin**: Find the index of the maximum or minimum value along a specified axis.
     ```python
     argmax_value = tf.argmax(X, axis=1)  # Index of maximum value along each row
     ```



### e. **Logarithm and Exponential**
   - **Logarithm**: Useful for computing log-loss (cross-entropy) or other functions.
     ```python
     log_tensor = tf.math.log(X)
     ```

   - **Exponential**: Compute the exponential of a tensor.
     ```python
     exp_tensor = tf.exp(X)
     ```

### 4. **GradientTape**

- TensorFlow’s **`GradientTape`** is used for **automatic differentiation**. It records operations performed on tensors so that you can compute the gradients of a loss function with respect to model parameters.

- This is essential for training models using gradient descent or other optimization algorithms.

In [12]:
## Example calculating gradient of x^2 + y^2 at point (3, 4)
# initial values
x = tf.Variable(3.0)
y = tf.Variable(4.0)
# record computation
with tf.GradientTape() as tape:
    z = x**2 + y**2
# calculate gradient
gradients = tape.gradient(z, [x, y])
gradients


[<tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=8.0>]

### 5. **Loss Functions**

- In machine learning, the **loss function** measures how well the model’s predictions match the actual labels.

- TensorFlow allows you to define custom loss functions, or you can use predefined ones like `tf.keras.losses.BinaryCrossentropy` for logistic regression.

- **Example**:
```python
# MSE regression loss function
def compute_loss(X, y, beta):
    z = tf.matmul(X, beta)
    return -tf.reduce_mean((y - z)**2)
```



### 6. **Optimizers**
- TensorFlow provides various **optimizers** that adjust the model parameters to minimize the loss function. The most commonly used optimizers include **Adam** and **Stochastic Gradient Descent (SGD)**.
- Optimizers update the trainable variables based on the computed gradients.
- **Example**:
```python
optimizer = tf.optimizers.SGD(learning_rate=0.1)
optimizer.apply_gradients(zip(gradients, [beta]))
```



### 7. **Training Loop**
- The training loop in TensorFlow involves:
1. **Forward pass**: Compute the predicted values and loss function.
2. **Backward pass**: Compute the gradients of the loss with respect to model parameters using `GradientTape`.
3. **Parameter update**: Use the optimizer to update the model parameters (e.g., weights) based on the gradients.
- This loop is repeated for a specified number of **epochs** until the model converges to a solution.
- **Example**:
```python
for epoch in range(num_epochs):
    with tf.GradientTape() as tape:
        loss = compute_loss(X, y, beta)
        gradients = tape.gradient(loss, [beta])
        optimizer.apply_gradients(zip(gradients, [beta]))
```


## EXERCISE

Find minimum of x^2 + y^2 using SGD algorithm and tensorflow.
Start at point (5,3)

In [ ]:
import tensorflow as tf
import numpy as np

# Define variables for x and y


# Define the optimizer Adam optimizer)


# Store the optimization trajectory
tf_trajectory = [[x.numpy(), y.numpy()]]

# Define the loss function
def loss_fn():
    # Compute the objective function 
    return 

# Run optimization for a few iterations
num_iterations = 200
for i in range(num_iterations):
    with tf.GradientTape() as tape:
        # Compute the loss
        loss = 
        # Compute gradients of x and y with respect to the loss
    
        # Apply gradients to update x and y

        # Store the optimization trajectory
        tf_trajectory.append(np.array([x.numpy(), y.numpy()]))

        # Print the current values of x, y, and the loss
        if i % 10 == 0:
            print(f"Iteration {i}: x = {x.numpy()}, y = {y.numpy()}, loss = {loss.numpy()}")

tf_trajectory = np.array(tf_trajectory)